spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: 'classpath:import-dev.sql'

  sql:
    init:
      mode: always
server:
  servlet:
    session:
      timeout: 1800 # 1800초 (30분)
      cookie:
        max-age: 1800 # 1800초 (30분)
        http-only: true
        same-site: None
        secure: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true


clientURL: http://localhost:3000
compilerURL: #컴파일러 서버 주소 입력